import "./globals.css";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });
import Providers from "@/store/provider";
export const metadata = {
  title: "Nextjs-Forms",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
     <Providers>
     <body className={inter.className}>
          {children}

          <Toaster />
        </body>
     </Providers>
      
      
    </html>
  );
}
